server:
  port: 1000

spring:
  application:
    name: spring-platform-cloud-producer

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

#开放所有页面节点 ，默认只开启了health、info两个节点
management:
  endpoints:
    web:
      exposure:
        exclude: '*'