spring:
  application:
    name: spring-platform-cloud-consumers
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 1002
feign:
  hystrix:
    enabled: true

#开放所有页面节点 ，默认只开启了health、info两个节点
management:
  endpoints:
    web:
      exposure:
        exclude: '*'
