server:
  port: 5000

eureka:
  client:
    service-url:
      defaultZone: http://129.204.1.173:8761/eureka/

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true  #设置serviceId小写，默认大写
      routes:
        - id: platform-account
          uri: lb://platform-account   #lb表示从注册中心获取服务
          predicates:
            - Path=/account/**         # 如果请求地址满足/account/**,则转发到user-server服务
          filters:
            - StripPrefix=1           # 去除原请求地址中的user

        - id: platform-auth
          uri: lb://platform-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1