server:
  port: 8763
eureka:
  instance:
    hostname: eureka.server3
    instance-id: ${eureka.instance.hostname}-${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka.server1:8761/eureka/,http://eureka.server2:8762/eureka/
