server:
  port: 5000
spring:
  application:
    name: spring-platform-cloud-zuul
zuul:
  routes:
    api-producer:
      path: /producer/**
      serviceId: spring-platform-cloud-producer

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/