zuul:
  # 默认过滤敏感头信息
  sensitiveHeaders:
  routes:
    cloud-account:
      path: /account/**
      service-id: platform-account
      strip-prefix: true
    cloud-auth:
      path: /auth/**
      serviceId: platform-auth
      strip-prefix: true
  host:
    max-per-route-connections: 60000
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
ribbon:
  ReadTimeout: 60000  # 单位毫秒数
  SocketTimeout: 60000
